### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by weikaiyun** [Ryan-Shz/FastWebView#10]
![image](https://user-images.githubusercontent.com/20124328/91631666-e83ce200-ea0d-11ea-9758-87b687e56654.png)

应该改成3吧

**Comment by Ryan-Shz** [comment]
哈哈，哥们很细致，是3👍

**Comment by weikaiyun** [comment]
还有个问题 想问下版主 就是那个webviewpool 现在有稳定版了吗
另外 PersistentCookieStore 我看这个类里面的 sp的操作直接就在主线程 不会有问题吗 如果比较频繁的话

**Comment by Ryan-Shz** [comment]
WebViewPool近期没有相关的提交。内部经过一段时间的测试，目前比较稳定。近期会再观察下，再找个时间传上来。

PersistentCookieStore中的保存操作主要是SP的apply，Cookie数据本身也不大，只是一些比较简单的字符串，通常情况下不会有问题。至少目前我还没遇到过哈。

**Comment by weikaiyun** [comment]
> WebViewPool近期没有相关的提交。内部经过一段时间的测试，目前比较稳定。近期会再观察下，再找个时间传上来。
> 
> PersistentCookieStore中的保存操作主要是SP的apply，Cookie数据本身也不大，只是一些比较简单的字符串，通常情况下不会有问题。至少目前我还没遇到过哈。

好的 谢谢版主
