### ISSUE TITLE
WebView无法弹出软键盘问题解决

### ISSUE THREAD

**Issue by yoiiis** [Ryan-Shz/FastWebView#17]
继承FastWebView时，注意构造方法 - defStyleAttr不能传0
public FastWebView(Context context, AttributeSet attrs) {
        super(context, attrs, 0);
}
另外可能还需要你设置如下属性requestFocus()

**Comment by Ryan-Shz** [comment]
所以老哥问题具体是啥呢？FastWebView主要解决的问题是处理页面缓存以达到二次提速，其他问题就把它当成是普通的WebView一样处理就好啦。控件内部也不宜写太多额外逻辑增加侵入性。
