### ISSUE TITLE
为什么要额外设置LiskLruCache

### ISSUE THREAD

**Issue by EvilerIT** [Ryan-Shz/FastWebView#18]
如果设置缓存模式为FastCacheMode.FORCE，为什么要加一个DiskResourceInterceptor拦截器呢？直接加大okttp缓存大小不就可以了么？反正底层用的都是DiskLruCache的逻辑？

**Comment by EvilerIT** [comment]
"况且，就算使用了HTTP协议缓存，在使用本地缓存之前，默认需要经过一次请求来校验缓存是否过期，如果在弱网环境下就会极大的拖慢H5加载速度。"
-------------------------
按我的理解，FastCacheMode.FORCE模式下，白名单mimetype的数据都会被okhttp缓存下来，这些数据都是静态数据，key应该是唯一的，应该是不需要校验有效时间的吧。

**Comment by EvilerIT** [comment]
> ## "况且，就算使用了HTTP协议缓存，在使用本地缓存之前，默认需要经过一次请求来校验缓存是否过期，如果在弱网环境下就会极大的拖慢H5加载速度。"
> 按我的理解，FastCacheMode.FORCE模式下，白名单mimetype的数据都会被okhttp缓存下来，这些数据都是静态数据，key应该是唯一的，应该是不需要校验有效时间的吧。

FastCacheMode.FORCE对应的LOAD_CACHE_ELSE_NETWORK，要么不用缓存，要么缓存时间无限长，感觉中间一层的DiskResourceInterceptor，没什么实际上的意义

**Comment by Ryan-Shz** [comment]
OkHttp的缓存实际上是HTTP缓存协议的实现，你可以看看CacheInterceptor，缓存不仅要受CacheControl的制约，还要受请求头、响应头里的缓存字段控制，比如：max-age，Etag等等。并且，正常情况下，要校验一次缓存是否可用。
-----------------------------------
而Force Mode会忽略HTTP缓存协议，无论你如何设置，我都会优先把白名单的数据缓存到自定义缓存中，下次优先从缓存读取，DiskResourceInterceptor的职责就是如此，同时Force Mode会禁止OkHttp缓存资源，也就是缓存完全由我们自定义接管。
