### ISSUE TITLE
有缓存不在白名单的数据。

### ISSUE THREAD

**Issue by topab** [Ryan-Shz/FastWebView#19]
默认配置也没有看见换到text/html的呀。能帮忙解答下吗，谢谢
![image](https://user-images.githubusercontent.com/60641837/112967277-b21b3880-917d-11eb-8a86-94995146e355.png)
![image](https://user-images.githubusercontent.com/60641837/112967591-02929600-917e-11eb-9f29-f87ed4073bd1.png)

**Comment by Ryan-Shz** [comment]
@topab 所有可缓存的资源都配置在ExtensionFilter中，可以看看DefaultExtensionFilter的实现
