### ISSUE TITLE
缓存文件夹换个路径就会蹦

### ISSUE THREAD

**Issue by EspoirX** [Ryan-Shz/FastWebView#2]

**Comment by Ryan-Shz** [comment]
我看下，可否帮忙贴一下崩溃日志？

**Comment by Ryan-Shz** [comment]
找到原因了，自定义CacheConfig时，只设置个缓存路径是不可以的，因为其他配置项没有设置默认值，这个我处理一下

**Comment by EspoirX** [comment]
白屏时间很长，希望你有好的方案解决一下

**Comment by EspoirX** [comment]
![image](https://user-images.githubusercontent.com/16240767/82978976-7de46200-a018-11ea-8a6b-ddad39c57556.png)
问题依然存在

**Comment by EspoirX** [comment]
没申请权限。。

**Comment by Ryan-Shz** [comment]
嗯，缓存路径默认是在应用私有目录下，如果你使用了SDCard的路径，需要单独申请一下权限

**Comment by Ryan-Shz** [comment]
> 白屏时间很长，希望你有好的方案解决一下

FastWebView主要解决的问题是网页二次加载提速，首次加载网页时跟原生webview并无差异。所以如果是首次打开网页，白屏时间会比较长。

还有一点是，目前默认的DefaultFilter不会缓存HTML文件，请求HTML文件时，每次都要进行缓存校验（HTTP缓存协议），也有导致白屏时间变长。这个其实需要做一些额外的优化，比如离线包。
