### ISSUE TITLE
请问缓存配置不是全局的吗？为啥放在fastWebView里啊？

### ISSUE THREAD

**Issue by budaowengd** [Ryan-Shz/FastWebView#21]
fastWebView.setCacheConfig(new CacheConfig.Builder()
        .setCacheDir(String fileDir)
        .setExtensionFilter(ExtensionFilter filter)
        .setVersion(int version)
        .setMemorySize(int size)
        .setDiskCacheSize(long diskCacheSize)
        .build());
不应该只初始化一次吗？ 现在如果想要使用缓存，每次创建WebVIew都要这样设置吗？

**Comment by Ryan-Shz** [comment]
@luoxiong94 目前是的，FastWebView的配置对象会随之页面的创建而创建，销毁而销毁，如果要统一初始化入口，你可以自己封装一下。

**Comment by Ryan-Shz** [comment]
配置应该是针对具体的WebView实例生效的，放在全局反而不合适
