### ISSUE TITLE
demo有空指针异常bug

### ISSUE THREAD

**Issue by topscommandroid** [Ryan-Shz/FastWebView#3]
在选中使用缓存池之后，进入webview加载完github后再点击任何一个git内的链接，然后点击返回键，崩溃

**Comment by Ryan-Shz** [comment]
你好，我这边测试后暂未复现，能否帮忙提供以下异常日志？

**Comment by appsming** [comment]
![Uploading image.png…]()
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.config.CacheConfig$Builder.<init>(CacheConfig.java:61)
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.WebViewCacheImpl.generateDefaultCacheConfig(WebViewCacheImpl.java:78)
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.WebViewCacheImpl.getCacheConfig(WebViewCacheImpl.java:74)
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.WebViewCacheImpl.getOfflineServer(WebViewCacheImpl.java:68)
06-13 10:04:28.554 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.WebViewCacheImpl.getResource(WebViewCacheImpl.java:50)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.InnerFastClient.loadFromWebViewCache(InnerFastClient.java:274)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.InnerFastClient.onIntercept(InnerFastClient.java:264)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.ryan.github.view.InnerFastClient.shouldInterceptRequest(InnerFastClient.java:245)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:321)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:527)
06-13 10:04:28.555 25328-25349/com.ryan.github.fastwebview W/System.err:     at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)

**Comment by Ryan-Shz** [comment]
WebViewPool建议暂时先不要使用，目前不是很稳定，有一些细节case需要处理，近期我也会做一下完整的测试，如果有兴趣的话，可以关注一下这个分支后续的提交：https://github.com/Ryan-Shz/FastWebView/tree/feature_pool_stability

**Comment by appsming** [comment]
> 你好，我这边测试后暂未复现，能否帮忙提供以下异常日志？
作者的设计思想蛮好的，很不错；建议把webview这块独立出来，因为在使用中，每个人对webivew都会有不同的使用，也有可能用户本身在项目中已实现了自己的webview， 所以建议抽象出接口回调或使用代理、适配器等设计模式；

**Comment by Ryan-Shz** [comment]
> > 你好，我这边测试后暂未复现，能否帮忙提供以下异常日志？
> > 作者的设计思想蛮好的，很不错；建议把webview这块独立出来，因为在使用中，每个人对webivew都会有不同的使用，也有可能用户本身在项目中已实现了自己的webview， 所以建议抽象出接口回调或使用代理、适配器等设计模式；

哈，感谢肯定，你可以看一下FastWebView这个类的源码，原生api调用很少，对现有项目的webview侵入性应该是很小的。如果有在使用，可以直接替换成FastWebView，如果有自己的webview基类，也可以继承FastWebView来扩展实现。

**Comment by appsming** [comment]
我的意思是library与实际使用的分离，降低耦合性；

**Comment by weikaiyun** [comment]
> WebViewPool建议暂时先不要使用，目前不是很稳定，有一些细节case需要处理，近期我也会做一下完整的测试，如果有兴趣的话，可以关注一下这个分支后续的提交：https://github.com/Ryan-Shz/FastWebView/tree/feature_pool_stability

版主 这个webviewpool现在有优化吗
