### ISSUE TITLE
 Cookie拦截器中的请求拦截器似乎没有正确工作

### ISSUE THREAD

**Issue by SkyGrass** [Ryan-Shz/FastWebView#4]
` fastCookieManager.setRequestCookieInterceptor(new CookieInterceptor() {
            @Override
            public List<Cookie> newCookies(HttpUrl url, List<Cookie> originCookies) {
                for (Cookie cookie : originCookies) {
                    Log.v(TAG, "request cookies: " + cookie.toString());
                }
                return originCookies;
            }
        });`
似乎没有正确工作。setResponseCookieInterceptor 拦截器倒是拦截了。

**Comment by Ryan-Shz** [comment]
感谢反馈，这两个Interceptor我写反了，已修复，你可以再试一下
