### ISSUE TITLE
这么好的一个开源库，居然这么少star？

### ISSUE THREAD

**Issue by PiPiCaptain** [Ryan-Shz/FastWebView#5]
我们项目使用您的开源库之后，网页加载速度得到明显提升。感谢您，想请您喝杯咖啡，不知道方不方便提供一个收款码？

**Comment by zhoushuangli** [comment]
这个好像没网的情况下还是不行

**Comment by Ryan-Shz** [comment]
> 我们项目使用您的开源库之后，网页加载速度得到明显提升。感谢您，想请您喝杯咖啡，不知道方不方便提供一个收款码？

哈哈，这个就不需要了，有帮助到你就行

**Comment by Ryan-Shz** [comment]
> 这个好像没网的情况下还是不行

具体是什么问题呢？如果你说的是离线加载，因为目前我们是不缓存html的，所以在无网络状态下，html文件是没办法加载的，所以加载不出来。你可以通过扩展ExtensionFilter，把Html也加入缓存白名单就可以实现离线加载了。但是可能会导致你们的Html页面无法更新，需要自己设计新的更新方案，比如通过离线包下发。

**Comment by SkyGrass** [comment]
> > 这个好像没网的情况下还是不行
> 
> 具体是什么问题呢？如果你说的是离线加载，因为目前我们是不缓存html的，所以在无网络状态下，html文件是没办法加载的，所以加载不出来。你可以通过扩展ExtensionFilter，把Html也加入缓存白名单就可以实现离线加载了。但是可能会导致你们的Html页面无法更新，需要自己设计新的更新方案，比如通过离线包下发。

我事先把一些资源文件内置在apk里，后面在资源拦截器里发现本地有就直接用本地资源。
我有点疑惑，如果本地都有资源文件了。是不是打破了本库优化二次加载的初衷？

**Comment by Ryan-Shz** [comment]
> > > 这个好像没网的情况下还是不行
> > 
> > 
> > 具体是什么问题呢？如果你说的是离线加载，因为目前我们是不缓存html的，所以在无网络状态下，html文件是没办法加载的，所以加载不出来。你可以通过扩展ExtensionFilter，把Html也加入缓存白名单就可以实现离线加载了。但是可能会导致你们的Html页面无法更新，需要自己设计新的更新方案，比如通过离线包下发。
> 
> 我事先把一些资源文件内置在apk里，后面在资源拦截器里发现本地有就直接用本地资源。
> 我有点疑惑，如果本地都有资源文件了。是不是打破了本库优化二次加载的初衷？

如果你们有一些基本不变的资源可以预置，是非常可行的。通过预置不仅可以二次提速，也可以缩短首次加载的时长。当然，因为预置，就失去了动态更新的能力，需要我们自己考虑新的更新方案。

**Comment by Ryan-Shz** [comment]
> 这个好像没网的情况下还是不行

你可以看一下最新的Demo，加上了离线加载的示例
