### ISSUE TITLE
有关闭Log的方法吗？

### ISSUE THREAD

**Issue by PiPiCaptain** [Ryan-Shz/FastWebView#8]
RT

**Comment by Ryan-Shz** [comment]
目前还没，这个我加一下 - -

**Comment by Ryan-Shz** [comment]
https://github.com/Ryan-Shz/FastWebView/commit/d815aed6f2926d9c152a95933f3046d998f38150 @PiPiCaptain
1.1.1版本

**Comment by PiPiCaptain** [comment]
@Ryan-Shz 好的
